All of the previously variables we've created are actually tensors. But you may also hear them referred to as their different names (the ones we gave them):<br>

scalar: a single number.<br>
vector: a number with direction (e.g. wind speed with direction).<br>
matrix: a 2-dimensional array of numbers.<br>
tensor: an n-dimensional arrary of numbers (where n can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector).<br>
To add to the confusion, the terms matrix and tensor are often used interchangably.<br>


Manipulating tensors (tensor operations)<br>
Finding patterns in tensors (numberical representation of data) requires manipulating them.<br>

Again, when building models in TensorFlow, much of this pattern discovery is done for you.<br>

Basic operations<br>
You can perform many of the basic mathematical operations directly on tensors using Pyhton operators such as, +, -, *.<br>

In [1]:
# Import TensorFlow
import tensorflow as tf

In [2]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

#Since we used tf.constant(), the original tensor is unchanged (the addition gets done on a copy).

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [3]:
# Original tensor unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [4]:
# Multiplication (known as element-wise multiplication)
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [5]:
# Subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

In [6]:
# Use the tensorflow function equivalent of the '*' (multiply) operator
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [7]:
# The original tensor is still unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

## Matrix mutliplication

In [8]:
# Matrix multiplication in TensorFlow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [9]:
# Matrix multiplication with Python operator '@'
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [10]:
# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [11]:
# Try to matrix multiply them (will error)
X @ Y

InvalidArgumentError: Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]

Trying to matrix multiply two tensors with the shape (3, 2) errors because the inner dimensions don't match.<br>

We need to either:<br>

Reshape X to (2, 3) so it's (2, 3) @ (3, 2).<br><br>
Reshape Y to (3, 2) so it's (3, 2) @ (2, 3).<br>
We can do this with either:<br>

tf.reshape() - allows us to reshape a tensor into a defined shape.<br>
tf.transpose() - switches the dimensions of a given tensor.<br>

In [12]:
# Let's try tf.reshape() first.
# Example of reshape (3, 2) -> (2, 3)
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]])>

In [13]:
# Try matrix multiplication with reshaped Y
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [14]:
# Example of transpose (3, 2) -> (2, 3)
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]])>

In [15]:
# Try matrix multiplication 
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [16]:
# You can achieve the same result with parameters
tf.matmul(a=X, b=Y, transpose_a=True, transpose_b=False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

## The dot product
Multiplying matrices by eachother is also referred to as the dot product.

You can perform the tf.matmul() operation using tf.tensordot().

In [17]:
# Perform the dot product on X and Y (requires X to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

You might notice that although using both reshape and tranpose work, you get different results when using each.

Let's see an example, first with tf.transpose() then with tf.reshape().

In [18]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

In [19]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [20]:
# Check shapes of Y, reshaped Y and tranposed Y
Y.shape, tf.reshape(Y, (2, 3)).shape, tf.transpose(Y).shape

(TensorShape([3, 2]), TensorShape([2, 3]), TensorShape([2, 3]))

In [21]:
# Check values of Y, reshape Y and tranposed Y
print("Normal Y:")
print(Y, "\n") # "\n" for newline

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


As you can see, the outputs of tf.reshape() and tf.transpose() when called on Y, even though they have the same shape, are different. <br>

This can be explained by the default behaviour of each method:<br>

tf.reshape() - change the shape of the given tensor (first) and then insert values in order they appear (in our case, 7, 8, 9, 10, 11, 12).<br>
tf.transpose() - swap the order of the axes, by default the last axis becomes the first, however the order can be changed using the perm parameter.<br>
So which should you use?<br><br>

Again, most of the time these operations (when they need to be run, such as during the training a neural network, will be implemented for you).<br>

But generally, whenever performing a matrix multiplication and the shapes of two matrices don't line up, you will transpose (not reshape) one of them in order to line them up.<br>

## Changing the datatype of a tensor<br>
Sometimes you'll want to alter the default datatype of your tensor.<br>

This is common when you want to compute using less precision (e.g. 16-bit floating point numbers vs. 32-bit floating point numbers).<br>

Computing with less precision is useful on devices with less computing capacity such as mobile devices (because the less bits, the less space the computations require).<br>

You can change the datatype of a tensor using tf.cast().<br>

In [22]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])

# Create a new tensor with default datatype (int32)
C = tf.constant([1, 7])
B, C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7])>)

In [23]:
# Change from float32 to float16 (reduced precision)
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [24]:
# Change from int32 to float32
C = tf.cast(C, dtype=tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>

## Getting the absolute value
Sometimes you'll want the absolute values (all values are positive) of elements in your tensors.

To do so, you can use tf.abs().

In [25]:
# Create tensor with negative values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [26]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

## Finding the min, max, mean, sum (aggregation)
You can quickly aggregate (perform a calculation on a whole tensor) tensors to find things like the minimum value, maximum value, mean and sum of all the elements.<br>

To do so, aggregation methods typically have the syntax reduce()_[action], such as:<br>

tf.reduce_min() - find the minimum value in a tensor.<br>
tf.reduce_max() - find the maximum value in a tensor (helpful for when you want to find the highest prediction probability).<br>
tf.reduce_mean() - find the mean of all elements in a tensor.<br>
tf.reduce_sum() - find the sum of all elements in a tensor.<br>
Note: typically, each of these is under the math module, e.g. tf.math.reduce_min() but you can use the alias tf.reduce_min().
Let's see them in action.<br>

In [28]:
import numpy as np
# Create a tensor with 50 random values between 0 and 100
E = tf.constant(np.random.randint(low=0, high=100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([71, 77, 16, 58, 30, 29,  6, 18, 60,  5, 44, 69, 21, 44, 34, 22, 63,
       35, 71, 53, 49, 33, 47, 51, 76, 10, 26,  0, 26, 16, 18, 67, 88, 89,
       61, 58, 69, 81, 24, 31, 12, 30, 77, 17, 89, 89, 14, 87, 10, 83])>

In [29]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [30]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=89>

In [31]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=45>

In [32]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2254>

In [49]:
# Add this line
E = tf.cast(E, dtype=tf.float32)
tf.math.reduce_std(
    E, axis=None, keepdims=False, name=None
)

<tf.Tensor: shape=(), dtype=float32, numpy=27.028755>

In [50]:
E = tf.constant(np.random.randint(low=0, high=100, size=50))
print(E)

# Add this line
E = tf.cast(E, dtype=tf.float32) # Convert to float 32

print(tf.math.reduce_std(E))
print(tf.math.reduce_variance(E))

tf.Tensor(
[40 52 54 60 74 45 22 57 46 77 30 44 89 66 99 41 80 15 66 61 63 10  2 37
 12 90 76 15 18 36  1 89 69 12 64 50 40 29 85 65 65 53 75 51 69  0 20 97
 10 79], shape=(50,), dtype=int32)
tf.Tensor(27.271963, shape=(), dtype=float32)
tf.Tensor(743.76, shape=(), dtype=float32)


## Finding the positional maximum and minimum
How about finding the position a tensor where the maximum value occurs?<br>

This is helpful when you want to line up your labels (say ['Green', 'Blue', 'Red']) with your prediction probabilities tensor (e.g. [0.98, 0.01, 0.01]).<br>

In this case, the predicted label (the one with the highest prediction probability) would be 'Green'.<br>

You can do the same for the minimum (if required) with the following:<br>

tf.argmax() - find the position of the maximum element in a given tensor.<br>
tf.argmin() - find the position of the minimum element in a given tensor.<br>

In [36]:
# Create a tensor with 50 values between 0 and 1
F = tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.32031626, 0.69523756, 0.83870204, 0.44652338, 0.71062149,
       0.19303039, 0.64471298, 0.05946428, 0.02481012, 0.38487287,
       0.46532279, 0.16708889, 0.92176318, 0.80834271, 0.54657145,
       0.87773159, 0.27018197, 0.73650574, 0.61600435, 0.46862664,
       0.78767754, 0.59655303, 0.09388303, 0.58353413, 0.6008842 ,
       0.46324581, 0.06666263, 0.335416  , 0.48451186, 0.53410278,
       0.44818596, 0.03564619, 0.97882549, 0.31427047, 0.84463305,
       0.97370749, 0.5009487 , 0.80966602, 0.43677619, 0.57521257,
       0.71834564, 0.26912812, 0.98748799, 0.27309271, 0.42937217,
       0.99314691, 0.89809593, 0.75370708, 0.17566398, 0.51266517])>

In [37]:
# Find the maximum element position of F
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=45>

In [38]:
# Find the minimum element position of F
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=8>

In [40]:
# Find the maximum element position of F
print(f"The maximum value of F is at position: {tf.argmax(F).numpy()}") 
print(f"The maximum value of F is: {tf.reduce_max(F).numpy()}") 
print(f"The minimum value of F is at position: {tf.argmin(F).numpy()}") 
print(f"The minimum value of F is: {tf.reduce_min(F).numpy()}") 
print(f"Using tf.argmax() to index F, the maximum value of F is: {F[tf.argmax(F)].numpy()}")
print(f"Are the two max values the same (they should be)? {F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy()}")

The maximum value of F is at position: 45
The maximum value of F is: 0.9931469142633724
The minimum value of F is at position: 8
The minimum value of F is: 0.024810120068397223
Using tf.argmax() to index F, the maximum value of F is: 0.9931469142633724
Are the two max values the same (they should be)? True


## Squeezing a tensor (removing all single dimensions)
If you need to remove single-dimensions from a tensor (dimensions with size 1), you can use tf.squeeze().

tf.squeeze() - remove all dimensions of 1 from a tensor.

In [42]:
# Create a rank 5 (5 dimensions) tensor of 50 numbers between 0 and 100
G = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))
G.shape, G.ndim, G

(TensorShape([1, 1, 1, 1, 50]),
 5,
 <tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=int32, numpy=
 array([[[[[63, 71, 63, 40, 43,  4, 25, 80, 13, 89, 72, 98, 28, 19, 70,
            89, 58, 65, 18, 96, 21, 62, 61, 31, 25, 27, 37, 99, 89, 75,
            40, 54, 22, 34, 41, 34,  1, 24, 15, 59, 62, 64,  9, 44, 23,
            35,  2, 25, 56, 54]]]]])>)

In [45]:
# Squeeze tensor G (remove all 1 dimensions)
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim , G_squeezed

(TensorShape([50]),
 1,
 <tf.Tensor: shape=(50,), dtype=int32, numpy=
 array([63, 71, 63, 40, 43,  4, 25, 80, 13, 89, 72, 98, 28, 19, 70, 89, 58,
        65, 18, 96, 21, 62, 61, 31, 25, 27, 37, 99, 89, 75, 40, 54, 22, 34,
        41, 34,  1, 24, 15, 59, 62, 64,  9, 44, 23, 35,  2, 25, 56, 54])>)

## One-hot encoding
If you have a tensor of indicies and would like to one-hot encode it, you can use tf.one_hot().

You should also specify the depth parameter (the level which you want to one-hot encode to).

In [51]:
# Create a list of indices
some_list = [0, 1, 2, 3]

# One hot encode them
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [52]:
# Specify custom values for on and off encoding
tf.one_hot(some_list, depth=4, on_value="We're live!", off_value="Offline")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b"We're live!", b'Offline', b'Offline', b'Offline'],
       [b'Offline', b"We're live!", b'Offline', b'Offline'],
       [b'Offline', b'Offline', b"We're live!", b'Offline'],
       [b'Offline', b'Offline', b'Offline', b"We're live!"]], dtype=object)>

## Squaring, log, square root
Many other common mathematical operations you'd like to perform at some stage, probably exist.

Let's take a look at:

tf.square() - get the square of every value in a tensor.<br>
tf.sqrt() - get the squareroot of every value in a tensor (note: the elements need to be floats or this will error).<br>
tf.math.log() - get the natural log of every value in a tensor (elements need to floats).<br>

In [53]:
# Create a new tensor
H = tf.constant(np.arange(1, 10))
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [54]:
# Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [56]:
# Find the squareroot (will error), needs to be non-integer
tf.sqrt(H)

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt]

In [57]:
# Change H to float32
H = tf.cast(H, dtype=tf.float32)
H

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [58]:
# Find the square root
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [59]:
# Find the log (input also needs to be float)
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Manipulating tf.Variable tensors
Tensors created with tf.Variable() can be changed in place using methods such as:

.assign() - assign a different value to a particular index of a variable tensor.<br>
.add_assign() - add to an existing value and reassign it at a particular index of a variable tensor.

In [60]:
# Create a variable tensor
I = tf.Variable(np.arange(0, 5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([0, 1, 2, 3, 4])>

In [61]:
# Assign the final value a new value of 50
I.assign([0, 1, 2, 3, 50])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([ 0,  1,  2,  3, 50])>

In [62]:
# The change happens in place (the last value is now 50, not 4)
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([ 0,  1,  2,  3, 50])>

In [63]:
# Add 10 to every element in I
I.assign_add([10, 10, 10, 10, 10])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([10, 11, 12, 13, 60])>

In [64]:
# Again, the change happens in place
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([10, 11, 12, 13, 60])>

## Tensors and NumPy
We've seen some examples of tensors interact with NumPy arrays, such as, using NumPy arrays to create tensors.<br>

Tensors can also be converted to NumPy arrays using:<br>

np.array() - pass a tensor to convert to an ndarray (NumPy's main datatype).<br>
tensor.numpy() - call on a tensor to convert to an ndarray.<br>
Doing this is helpful as it makes tensors iterable as well as allows us to use any of NumPy's methods on them.<br>

In [65]:
# Create a tensor from a NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [66]:
# Convert tensor J to NumPy with np.array()
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [68]:
# Convert tensor J to NumPy with .numpy()
J.numpy(), type(J.numpy())

#By default tensors have dtype=float32, where as NumPy arrays have dtype=float64

(array([ 3.,  7., 10.]), numpy.ndarray)

In [69]:
# Create a tensor from NumPy and from an array
numpy_J = tf.constant(np.array([3., 7., 10.])) # will be float64 (due to NumPy)
tensor_J = tf.constant([3., 7., 10.]) # will be float32 (due to being TensorFlow default)
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

## Using @tf.function

In the @tf.function decorator case, it turns a Python function into a callable TensorFlow graph. Which is a fancy way of saying, if you've written your own Python function, and you decorate it with @tf.function, when you export your code (to potentially run on another device), TensorFlow will attempt to convert it into a fast(er) version of itself (by making it part of a computation graph).

In [70]:
# Create a simple function
def function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
function(x, y)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [71]:
# Create the same function and decorate it with tf.function
@tf.function
def tf_function(x, y):
  return x ** 2 + y

tf_function(x, y)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

## Finding access to GPUs
We've mentioned GPUs plenty of times throughout this notebook.

So how do you check if you've got one available?

You can check if you've got access to a GPU using tf.config.list_physical_devices().

In [72]:
print(tf.config.list_physical_devices('GPU'))

[]


In [73]:
!nvidia-smi

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.
